SET IDENTITY_INSERT [dbo].[Actors] ON
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (1, N'Keanu Reeves', 1964, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (2, N'Laurence Fishburne', 1961, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (3, N'Joe Pantoliano', 1951, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (4, N'Julian Arahanga', 1972, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (5, N'Marcus Chong', 1967, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (6, N'Paul Goddard', 1963, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (7, N'Anthony Ray Parker', 1958, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (8, N'Carrie-Anne Moss', 1967, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (9, N'Hugo Weaving', 1960, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (10, N'Gloria Foster', 1933, N'2001', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (11, N'Belinda McClory', 1968, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (12, N'Robert Taylor', 1963, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (13, N'Ada Nicodemou', 1977, N'NULL', N'The Matrix')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (14, N'Leonardo DiCaprio', 1974, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (15, N'Kate Winslet', 1975, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (16, N'Billy Zane', 1966, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (17, N'Kathy Bates', 1948, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (18, N'Frances Fisher', 1952, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (19, N'Gloria Stuart', 1910, N'2010', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (20, N'Bill Paxton', 1955, N'2017', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (21, N'Bernard Hill', 1944, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (22, N'David Warner', 1941, N'2022', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (23, N'Victor Garber', 1949, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (24, N'Jonathan Hyde', 1948, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (25, N'Suzy Amis', 1962, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (26, N'Danny Nucci', 1968, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (27, N'Jason Barry', 1972, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (28, N'Ewan Stewart', 1957, N'NULL', N'Titanic')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (29, N'Tom Cruise', 1962, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (30, N'Tim Robbins', 1958, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (31, N'Kelly McGillis', 1957, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (32, N'Val Kilmer', 1959, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (33, N'Anthony Edwards', 1962, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (34, N'Tom Skerritt', 1933, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (35, N'Michael Ironside', 1950, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (36, N'John Stockwell', 1961, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (37, N'Barry Tubb', 1963, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (38, N'Rick Rossovich', 1957, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (39, N'Clarence Gilyard Jr.', 1955, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (40, N'Whip Hubley', 1957, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (41, N'James Tolkan', 1931, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (42, N'Meg Ryan', 1961, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (43, N'Adrian Pasdar', 1965, N'NULL', N'Top Gun')
INSERT INTO [dbo].[Actors] ([ActorID], [Name], [BirthYear], [DeathYear], [Played_in]) VALUES (44, N'Duke Stroud', 1938, N'NULL', N'Top Gun')
SET IDENTITY_INSERT [dbo].[Actors] OFF
